package main

import (
	"fmt"
	"go/format"
	"hygoal/tools/protogen/internal"
	"os"
	"path"
	"strings"

	"github.com/alecthomas/kong"
	"github.com/incu6us/goimports-reviser/v3/reviser"
)

var CLI struct {
	Input  string `help:"Input directory containing .proto files." short:"i" required:"" type:"path"`
	Output string `help:"Output directory for generated Go files." short:"o" required:"" type:"path"`
}

func main() {
	ctx := kong.Parse(&CLI)
	_ = ctx

	dir, err := os.ReadDir(CLI.Input)
	if err != nil {
		panic(err)
	}

	fileAsts := make([]*protogen.FileNode, 0)

	for _, entry := range dir {
		if entry.IsDir() {
			fmt.Printf("Skipping directory: %s\n", entry.Name())
			continue
		}
		if entry.Type().IsRegular() && len(entry.Name()) > 6 && strings.HasSuffix(entry.Name(), ".schema") {
			data, err := os.ReadFile(CLI.Input + "/" + entry.Name())
			if err != nil {
				panic(err)
			}

			parser := protogen.NewParser(string(data))
			ast, err := parser.Parse()

			if err != nil {
				panic(protogen.FormatParseError(err, entry.Name()))
			}

			fileAsts = append(fileAsts, ast)

			fmt.Printf("Parsed file: %s\n", entry.Name())
		} else {
			fmt.Printf("Skipping non-proto file: %s\n", entry.Name())
		}
	}

	combinedAst := &protogen.FileNode{
		Expressions: make([]protogen.Node, 0),
	}

	for _, ast := range fileAsts {
		combinedAst.Expressions = append(combinedAst.Expressions, ast.Expressions...)
	}

	finalCode := fmt.Sprintf("// Code generated by protogen. DO NOT EDIT.\n\npackage %s\n\n", path.Base(CLI.Output))
	finalCode += "type Packet interface {\n\tID() uint32\n}\n\n"

	code, err := protogen.GenerateGoCode(combinedAst)
	if err != nil {
		panic(err)
	}
	finalCode += code + "\n\n"

	outfile := CLI.Output + "/generated.go"

	err = os.WriteFile(outfile, []byte(finalCode), 0644)
	if err != nil {
		panic(err)
	}

	formattedCode, err := format.Source([]byte(finalCode))
	if err != nil {
		panic(err)
	}

	err = os.WriteFile(outfile, formattedCode, 0644)
	if err != nil {
		panic(err)
	}

	sourceFile := reviser.NewSourceFile("hygoal", outfile)
	_, _, _, err = sourceFile.Fix()

	fmt.Printf("Generated Go code written to %s/generated.go\n", CLI.Output)
}
